from buffer import Buffer

b = Buffer(policy='ASDASDSA')
print(b)
b.insert("Primero")
print(b.show_last())
b.insert("Segundo")
print(b.show_last())
b.insert(None)
print(b.show_last())
b.insert("Cuarto")
print(b.show_last())
b.insert("Ultimo")
print(b.show_last())
print("Ahora vamos a extraer")
print(b.extract())
print(b.show_last())
print(b.extract())
b.insert("final")
print(b.show_last())
b.insert("lego")
print(b.show_last())
b.insert("Pila")
print(b.show_last())
print(b.extract())
print(b.extract())
print(b.buffersize())
